server:
  port: 8703
spring:
  application:
    name: swag-discovery

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://swag-discovery:8703/eureka/
#      defaultZone: http://localhost:8703/eureka/